### PR TITLE
add variable to be able to customize appender pattern in logback file

### PR DESCRIPTION
**Pull request by ylorenzati**

### CODE REVIEW

**Comment by JayH5** [comment]
Hi @ylorenza, thank you for the PR.

I've fixed the build in the `develop` branch, so you can merge that branch into yours to get builds working.

This will need a basic test as well.

But before we get to that, this module hasn't really been maintained much recently. We don't really use it much anymore as we've largely moved to DC/OS which handles this kind of stuff for Marathon. We will be looking for a new maintainer for the module if there are still people who want to use it.

I'm going to do what I've done before in this situation and say that if this functionality is important to you, we can merge this PR (after fixing any issues) and I will do one more release of the module to Puppet Forge, but after that you can consider this code unmaintained until somebody else takes up ownership.

**Comment by ylorenzati** [comment]
Thanks for you're answer.

There is no rush. I'made this PR because I'need that, but also to see if there is still someone on this repository.

No need to merge, I will write my own puppet module.

Just question : you use puppet to install dcos ?

**Comment by jerith** [comment]
> Just question : you use puppet to install dcos ?

We do, but the puppet code for that is a mess and mostly tied to the specifics of our infrastructure. There are some hacks for making things work on Debian, too.

The basic idea we use is this:
 * All machines get a base setup that includes docker (if appropriate), a few system packages (`curl`, etc.), and some general system configuration.
 * The bootstrap machine pulls down the appropriate `dcos_generate_config.sh`, writes out the installer configs, and `exec`s a script that does most of what's documented in [the installer docs](https://dcos.io/docs/1.9/installing/custom/advanced/).
 * The master and agent machines `exec` a script that pulls `dcos_install.sh` from the bootstrap machine and then runs it with the appropriate parameter for the machine type.
 * Various other machines (databases, etc.) are configured similarly, but aren't really part of the DC/OS bits.

I have a TODO item for cleaning that up and using some of the newer puppet 4 features to simplify the configuration, but it's unfortunately not particularly high on my priority list.

**Comment by ylorenzati** [comment]
OK, thank again, and thank for you're feedback on dcos with puppet.
I close my pr

**Pull request closed without merging**
